//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankEntities2 : DbContext
    {
        public BankEntities2()
            : base("name=BankEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Argent_Comptant> Argent_Comptant { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Compte_Bancaire> Compte_Bancaire { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
