//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string CCLIENT { get; set; }
        public int Numero_de_transaction { get; set; }
        public Nullable<decimal> Depot { get; set; }
        public Nullable<decimal> Retrait { get; set; }
        public string No_Compte { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Compte_Bancaire Compte_Bancaire { get; set; }
    }
}
